name: Run Tests
on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:


jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install libreoffice-writer=1:7.3.4-0ubuntu0.22.04.1 python3-uno=1:7.3.4-0ubuntu0.22.04.1 python3=3.10.4-0ubuntu2 python3-pip=22.0.2+dfsg-1 python3-venv=3.10.4-0ubuntu2 --no-install-recommends -y
          ./start_server &
      - name: Run tests
        run: python3 -m unittest tests/api_test.py
